project:
  type: website

website:
  title: "Mihai Ion"
  navbar:
    left:
      - file: index.qmd
        text: "Home"
      - file: research.qmd
        text: "Research"
      - file: teaching.qmd
        text: "Teaching"
      - href: "CV/Mihai Ion CV.pdf"
        text: "CV"

  #sidebar:
    #- title: "Teaching"
    #  style: "docked"
    #  background: "light"
    #  contents:
    #    - teaching.qmd
    #    - section: "FIN 525"
    #      contents: "teaching/FIN 525/lectures"
    #    - section: "FIN 421"
    #      contents: "teaching/FIN 421/lectures"
    #- title: "Home"
    #- title: "Research"

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    page-layout: full
    link-external-newwindow: true
    grid:
      sidebar-width: 400px


