# Publications 
***

### [Policy Uncertainty and Corporate Investment](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2188090) 
with Huseyin Gulen

* **Review of Financial Studies**, Vol. 29 (3), 2016, 523-564
* Lead Article, Editor's Choice Article
* Mentions: [Economic Report of the President of the United States (2023)](https://www.whitehouse.gov/wp-content/uploads/2023/03/ERP-2023.pdf?_ga=2.108324618.98294196.1680906187-1215979928.1680906187), [The Economist (paywall)](https://www.economist.com/business/2016/11/19/uncertain-business?frsc=dg%7Ca)
* <details> <summary>Abstract</summary>\
        Using the policy uncertainty index of Baker, Bloom, and Davis (2013), we document a strong negative relationship between firm-level capital investment and the aggregate level of uncertainty associated with future policy and regulatory outcomes. More importantly, we find evidence that the relation between policy uncertainty and capital investment is not uniform in the cross section, being significantly stronger for firms with a higher degree of investment irreversibility and for firms which are more dependent on government spending. Our results lend empirical support to the notion that policy uncertainty can depress corporate investment by inducing precautionary delays due to investment irreversibility.
</details>


<!-- -->

### [Does Policy Uncertainty Affect Mergers and Acquisitions?](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2813466)
with Alice Bonaime and Huseyin Gulen


* **Journal of Financial Economics**, Vol. 129 (3), 2018, 531-558
* <details> <summary>Abstract</summary>\
        Political and regulatory uncertainty is strongly negatively associated with merger and acquisition activity at the macro and firm levels. The strongest effects are for uncertainty regarding taxes, government spending, monetary and fiscal policies, and regulation. Consistent with a real options channel, the effect is exacerbated for less reversible deals and for firms whose product demand or stock returns exhibit greater sensitivity to policy uncertainty, but attenuated for deals that cannot be delayed due to competition and for deals that hedge firm-level risk. Contractual mechanisms (deal premiums, termination fees, MAC clauses) unanimously point to policy uncertainty increasing the target’s negotiating power.
</details>
<!-- -->

### [Exports, Investment, and Policy Uncertainty](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2833536)
with Andrew Greenland and John Lopresti


* **Canadian Journal of Economics**, Vol. 52 (3), 2019, 1248-1288
* <details> <summary>Abstract</summary>\
        Building on a literature that underscores the value of delaying investment in the face of uncertainty, we study how policy uncertainty in fifteen large economies affects trade flows into these countries. We show that high levels of uncertainty in destination markets are associated with significantly lower exports to those markets. Furthermore, consistent with a model in which firms face irreversible costs to export, we show that this effect is entirely driven by a reduction in the entry of new products. Finally, we find that the effect of uncertainty on trade flows is significantly stronger when trade costs are less reversible.
</details>
<!-- -->

### [The Use of Asset Growth in Empirical Asset Pricing Models](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3026534)
with Michael Cooper and Huseyin Gulen


* **Journal of Financial Economics**, Vol. 151, 2024, 103746
* <details> <summary>Abstract</summary>\
     We show that the performance of the new factor models of Hou, Xue, and Zhang (2015) and Fama and French (2015) depends crucially on how their investment factor is constructed. Both models use growth in total assets to measure investment. Their ability to price the cross-section of returns decreases significantly when the investment factor is constructed using traditional investment measures, or measures that also account for investment in intangibles. In contrast, we find that factors based on growth in inventory and accounts receivable contain the bulk of the pricing information in the asset growth factor. We show evidence that the superior performance of the asset growth factor seems to be attributable to its ability to capture aggregate shocks to equity financing costs.
</details>
<!-- -->

### [Credit Cycles, Expectations, and Corporate Investment](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3369295)
with Huseyin Gulen, Candace Jens, and Stefano Rossi


* **Review of Financial Studies**, Vol. 37 (11), 2024, 3335–3385
* <details> <summary>Abstract</summary>\
        We provide a systematic empirical assessment of the Minsky (1957) hypothesis that business fluctuations stem from irrational swings in expectations. Using predictable firm-level forecast errors, we build an aggregate index of irrational expectations and use it to provide three sets of results. First, we show that our index predicts aggregate credit cycles. Next, we show that these predictable credit cycles drive cycles in firm-level debt issuance and investment and similar cycles between financially constrained and unconstrained firms, as Minsky (1957, 1977) predicts. Finally, we show more pronounced cycles in firm-level financing and investment for firms with ex ante more optimistic expectations.
</details>
<!-- -->

### [Using Equity Market Reactions to Infer Exposure to Trade Liberalization](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3649874)
with Andrew Greenland, John Lopresti, and Peter Schott


* **Journal of International Economics**, Vol. 152, 2024, 104000
* <details> <summary>Abstract</summary>\
        We propose a method for identifying exposure to changes in trade policy based on asset prices that has several advantages over standard measures: it encompasses all avenues of exposure, it is natively firm-level, it yields estimates for both goods and service producers, and it can be used to study reductions in difficult-to-quantify non-tariff barriers in a way that controls naturally for broader macroeconomic shocks. Applying our method to two well-studied US trade liberalizations provides new insight into service sector responses to trade liberalizations as well as dramatically different responses among small versus large firms, even within narrow industries.
</details>
<!-- -->


# Working Papers
***

### Financing Innovation in Drug Development 
with Henry Conter 

* <details> <summary>Abstract</summary>\
        Using a comprehensive, project-level database on drug development programs, we examine the link between external financing markets and drug-approval outcomes. We show evidence that the exposure of drug development projects to external financing conditions has increased over time. Specifically, we show that the clinical trial process has become riskier, significantly longer, and increasingly dominated by smaller sponsors. More directly, we document a significant increase in the percentage of projects explicitly citing lack of funding as the reason for termination, and show that these terminations correlate strongly with periods of rising equity financing costs. Furthermore, we show evidence of growing clustering in drug development programs with respect to the biological targets they pursue. This trend is counteracted by a significant increase in the total number of targets available, resulting in lower average pairwise correlations in approval outcomes over time. As a result, moderately-sized portfolios of around 20 drugs consistently provide average returns that are twice as large and standard deviations that are 60\% lower than the average drug-development project in our sample.
</details>

### Using Large Language Models to Identify Product Markets

* Draft coming soon


### [Policy Uncertainty, Corporate Risk-Taking, and CEO Incentives](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3039734)
with David Yin


* <details> <summary>Abstract</summary>\
        We show evidence that CEO risk-taking incentives represent a key mechanism through which policy uncertainty impacts the real economy. We document that high levels of policy uncertainty are associated with significantly lower future stock return volatility. This relation is stronger (more negative) for firms where the CEO has higher compensation delta or less transferable skills, and is weaker when the CEO has higher compensation vega. Furthermore, when policy uncertainty is high, firms are more likely to use financial hedging instruments and engage in more diversifying mergers, and CEOs sell more own-firm shares and exercise fewer options.
</details>
<!-- -->

# Permanent Working Papers
***

### Asset Pricing Anomalies and Time-Varying Expected Returns

<!-- (./papers/regime_switching.pdf)
* <details> <summary>Abstract</summary>\
        I analyze the expected returns associated with twelve well cited asset pricing anomalies using two different methods of detecting time-variation in expected returns. First, I jointly estimate the expected equity premium and the time-varying market betas of anomaly portfolios in a conditional CAPM framework and I find that nine of the twelve anomaly spread portfolios exhibit significantly higher conditional market betas in periods when the equity premium is at its highest. Second, using a regime switching model with time varying transition probabilities to estimate the joint distribution of anomaly expected returns. I find that the spread portfolios of six out of the twelve anomalies have significantly higher expected returns in recessionary and high-volatility states of the world. Overall, my findings support the hypothesis that some portion of the cross-sectional variation in average returns associated with all but the momentum and reversal anomalies is attributable to variation in risk. The strongest support is received by the size and book-to-market anomalies, while the remaining anomalies fall somewhere in between.
</details>

-->