<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mihai Ion - L15: Linear regression intro</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Mihai Ion</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../research.html" rel="" target="">
 <span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching.html" rel="" target="">
 <span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../CV/Mihai Ion CV.pdf" rel="" target="">
 <span class="menu-text">CV</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#preliminaries" id="toc-preliminaries" class="nav-link active" data-scroll-target="#preliminaries">Preliminaries</a></li>
  <li><a href="#linear-regression-basics" id="toc-linear-regression-basics" class="nav-link" data-scroll-target="#linear-regression-basics">Linear regression basics</a>
  <ul class="collapse">
  <li><a href="#a1.-linearity" id="toc-a1.-linearity" class="nav-link" data-scroll-target="#a1.-linearity">A1. Linearity</a></li>
  <li><a href="#a2.-mean-independence" id="toc-a2.-mean-independence" class="nav-link" data-scroll-target="#a2.-mean-independence">A2. Mean independence</a></li>
  <li><a href="#a3.-homoskedastic-and-uncorrelated-disturbances" id="toc-a3.-homoskedastic-and-uncorrelated-disturbances" class="nav-link" data-scroll-target="#a3.-homoskedastic-and-uncorrelated-disturbances">A3. Homoskedastic and uncorrelated disturbances</a></li>
  <li><a href="#a4.-full-rank" id="toc-a4.-full-rank" class="nav-link" data-scroll-target="#a4.-full-rank">A4. Full rank</a></li>
  </ul></li>
  <li><a href="#regression-fitting-ordinary-least-squares-ols" id="toc-regression-fitting-ordinary-least-squares-ols" class="nav-link" data-scroll-target="#regression-fitting-ordinary-least-squares-ols">Regression fitting: ordinary least squares (OLS)</a>
  <ul class="collapse">
  <li><a href="#example-1-estimating-a-stocks-alpha-and-beta-using-the-market-model" id="toc-example-1-estimating-a-stocks-alpha-and-beta-using-the-market-model" class="nav-link" data-scroll-target="#example-1-estimating-a-stocks-alpha-and-beta-using-the-market-model">Example 1: estimating a stock’s alpha and beta using the market model</a></li>
  <li><a href="#example-2-estimating-a-stocks-alpha-and-betas-using-the-fama-french-three-factor-model" id="toc-example-2-estimating-a-stocks-alpha-and-betas-using-the-fama-french-three-factor-model" class="nav-link" data-scroll-target="#example-2-estimating-a-stocks-alpha-and-betas-using-the-fama-french-three-factor-model">Example 2: estimating a stock’s alpha and beta(s) using the Fama-French three-factor model</a></li>
  </ul></li>
  <li><a href="#interpreting-regression-results" id="toc-interpreting-regression-results" class="nav-link" data-scroll-target="#interpreting-regression-results">Interpreting regression results</a>
  <ul class="collapse">
  <li><a href="#coefficients" id="toc-coefficients" class="nav-link" data-scroll-target="#coefficients">Coefficients</a></li>
  <li><a href="#statistical-significance" id="toc-statistical-significance" class="nav-link" data-scroll-target="#statistical-significance">Statistical significance</a></li>
  <li><a href="#the-r-squared-coefficient" id="toc-the-r-squared-coefficient" class="nav-link" data-scroll-target="#the-r-squared-coefficient">The R-squared coefficient</a></li>
  <li><a href="#diagnostics-bottom-of-the-table" id="toc-diagnostics-bottom-of-the-table" class="nav-link" data-scroll-target="#diagnostics-bottom-of-the-table">Diagnostics (bottom of the table):</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">L15: Linear regression intro</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="preliminaries" class="level1">
<h1>Preliminaries</h1>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> yfinance <span class="im">as</span> yf</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas_datareader <span class="im">as</span> pdr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Load Fama-French factor data:</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>ff3f <span class="op">=</span> pdr.DataReader(<span class="st">'F-F_Research_Data_Factors'</span>, <span class="st">'famafrench'</span>, <span class="st">'2012-01-01'</span>)[<span class="dv">0</span>]<span class="op">/</span><span class="dv">100</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>ff3f.head(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Mkt-RF</th>
<th data-quarto-table-cell-role="th">SMB</th>
<th data-quarto-table-cell-role="th">HML</th>
<th data-quarto-table-cell-role="th">RF</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2012-01</td>
<td>0.0505</td>
<td>0.0203</td>
<td>-0.0097</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2012-02</td>
<td>0.0442</td>
<td>-0.0185</td>
<td>0.0043</td>
<td>0.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Download monthly prices (keep only Adjusted Close prices):</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>firm_prices <span class="op">=</span> yf.download(<span class="st">'TSLA'</span>, <span class="st">'2012-12-01'</span>, <span class="st">'2020-12-31'</span>, interval <span class="op">=</span> <span class="st">'1mo'</span>)[<span class="st">'Adj Close'</span>].dropna().to_frame()</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>firm_prices.head(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[*********************100%***********************]  1 of 1 completed</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Adj Close</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2012-12-01</td>
<td>2.258000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2013-01-01</td>
<td>2.500667</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Calculate monthly returns, drop missing and rename “Adj Close” to “TSLA”:</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>firm_ret <span class="op">=</span> firm_prices.pct_change().dropna().rename(columns <span class="op">=</span> {<span class="st">'Adj Close'</span>: <span class="st">'TSLA'</span>})</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>firm_ret.head(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TSLA</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2013-01-01</td>
<td>0.107470</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2013-02-01</td>
<td>-0.071448</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We need to merge <code>firm_ret</code> with <code>ff3f</code> but note that their dates look different. Check their format first:</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>firm_ret.index.dtype</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>dtype('&lt;M8[ns]')</code></pre>
</div>
</div>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ff3f.index.dtype</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">
<pre><code>period[M]</code></pre>
</div>
</div>
<p>Convert index of <code>firm_ret</code> to monthly period, to match the date format un <code>ff3f</code>:</p>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>firm_ret.index <span class="op">=</span> firm_ret.index.to_period(<span class="st">'M'</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>firm_ret.head(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TSLA</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2013-01</td>
<td>0.107470</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2013-02</td>
<td>-0.071448</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Merge the two datasets:</p>
<div class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> firm_ret.join(ff3f)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>data.head(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TSLA</th>
<th data-quarto-table-cell-role="th">Mkt-RF</th>
<th data-quarto-table-cell-role="th">SMB</th>
<th data-quarto-table-cell-role="th">HML</th>
<th data-quarto-table-cell-role="th">RF</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2013-01</td>
<td>0.107470</td>
<td>0.0557</td>
<td>0.0033</td>
<td>0.0096</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2013-02</td>
<td>-0.071448</td>
<td>0.0129</td>
<td>-0.0028</td>
<td>0.0011</td>
<td>0.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'const'</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="35">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TSLA</th>
<th data-quarto-table-cell-role="th">Mkt-RF</th>
<th data-quarto-table-cell-role="th">SMB</th>
<th data-quarto-table-cell-role="th">HML</th>
<th data-quarto-table-cell-role="th">RF</th>
<th data-quarto-table-cell-role="th">const</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2013-01</td>
<td>0.107470</td>
<td>0.0557</td>
<td>0.0033</td>
<td>0.0096</td>
<td>0.0000</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2013-02</td>
<td>-0.071448</td>
<td>0.0129</td>
<td>-0.0028</td>
<td>0.0011</td>
<td>0.0000</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2013-03</td>
<td>0.087855</td>
<td>0.0403</td>
<td>0.0081</td>
<td>-0.0019</td>
<td>0.0000</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2013-04</td>
<td>0.424914</td>
<td>0.0155</td>
<td>-0.0236</td>
<td>0.0045</td>
<td>0.0000</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2013-05</td>
<td>0.810706</td>
<td>0.0280</td>
<td>0.0173</td>
<td>0.0263</td>
<td>0.0000</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2020-08</td>
<td>0.741452</td>
<td>0.0763</td>
<td>-0.0022</td>
<td>-0.0296</td>
<td>0.0001</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2020-09</td>
<td>-0.139087</td>
<td>-0.0363</td>
<td>0.0004</td>
<td>-0.0268</td>
<td>0.0001</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2020-10</td>
<td>-0.095499</td>
<td>-0.0210</td>
<td>0.0437</td>
<td>0.0422</td>
<td>0.0001</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2020-11</td>
<td>0.462736</td>
<td>0.1247</td>
<td>0.0581</td>
<td>0.0213</td>
<td>0.0001</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2020-12</td>
<td>0.243252</td>
<td>0.0463</td>
<td>0.0489</td>
<td>-0.0150</td>
<td>0.0001</td>
<td>1</td>
</tr>
</tbody>
</table>

<p>96 rows × 6 columns</p>
</div>
</div>
</div>
</section>
<section id="linear-regression-basics" class="level1">
<h1>Linear regression basics</h1>
<p>A linear regression is a statistical model, which means it is a set of assumptions about the relation between two or more variables. In particular, the standard linear regression assumptions are (we restrict ourselves to two variables X and Y for now):</p>
<section id="a1.-linearity" class="level2">
<h2 class="anchored" data-anchor-id="a1.-linearity">A1. Linearity</h2>
<p>The relation between the variables is assumed to be linear in parameters:</p>
<p><span class="math display">\[Y_t = \alpha + \beta \cdot X_t + \epsilon_t \]</span></p>
<p>Note that “linear in parameters” means the function that describes the relation between X and Y (the equation above) is linear with respect to <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> (e.g.&nbsp;<span class="math inline">\(Y = \alpha \cdot X^{\beta} + \epsilon\)</span> is not linear in parameters). It does not mean that the relation needs to be linear with respect to X (e.g.&nbsp;<span class="math inline">\(Y = \alpha + \beta \cdot X^2 + \epsilon\)</span> is still linear in parameters).</p>
<p>Before we cover the remaining assumptions, a bit of terminology:</p>
<ul>
<li><p>Y is commonly referred to as the “dependent”, or “explained” or “endogenous” variable</p></li>
<li><p>X is commonly referred to as the “independent”, or “explanatory”, or “exogenous” variable (though, remember, that X can stand for more than one variables)</p></li>
<li><p><span class="math inline">\(\epsilon\)</span> is commonly referred to as the “residual” of the regression, or the “error” term, or the “disturbance” term</p></li>
<li><p><span class="math inline">\(\alpha\)</span> (alpha) and <span class="math inline">\(\beta\)</span> (beta) are the “coefficients” or “parameters” of the regression. <strong>The outcome of “running a regression” is to calculate estimates for these alpha and beta coefficients.</strong></p></li>
<li><p>the t subscript is meant to represent the fact that we observe multiple realizations of the X and Y variables, and the linear relation is assumed to hold for each set of realizations (different t’s can represent different points in time, or different firms, different countries, etc). Going forward in this section, we will assume that t stands for time, to make the interpretation clearer.</p></li>
</ul>
</section>
<section id="a2.-mean-independence" class="level2">
<h2 class="anchored" data-anchor-id="a2.-mean-independence">A2. Mean independence</h2>
<p>This assumption states that the independent variable(s) X convey no information about the disturbance terms (<span class="math inline">\(\epsilon\)</span>’s). Technically, we write this assumption as:</p>
<p><span class="math display">\[E[\epsilon_t | X] = 0\]</span></p>
<p>This is also called the “strict exogeneity” assumption. When this condition is not satisfied, we say that our regression model has an <strong>endogeneity problem</strong>.</p>
</section>
<section id="a3.-homoskedastic-and-uncorrelated-disturbances" class="level2">
<h2 class="anchored" data-anchor-id="a3.-homoskedastic-and-uncorrelated-disturbances">A3. Homoskedastic and uncorrelated disturbances</h2>
<p>This assumption states that all disturbance terms have the same variance (i.e.&nbsp;they are “homoskedastic”):</p>
<p><span class="math display">\[ Var[\epsilon_t | X] = \sigma^2                 \text{  , for all observations $t$} \]</span></p>
<p>When this assumption is not satisfied, we say we have a <strong>heteroskedasticity problem</strong>.</p>
<p>The standard linear regression model also assumes that any two disturbance terms are uncorrelated with each other:</p>
<p><span class="math display">\[ Cov [\epsilon_{t_1}, \epsilon_{t_2}] = 0 \text{ , for all $t_1 \neq t_2$}\]</span></p>
</section>
<section id="a4.-full-rank" class="level2">
<h2 class="anchored" data-anchor-id="a4.-full-rank">A4. Full rank</h2>
<p>This assumption states that there are no exact linear relationships between the explanatory variables X (when there are two or more such variables). When this assumption is not satisfied, we say we have a <strong>multicollinearity problem</strong>.</p>
<p>In the next few lectures, we will cover strategies that we can use when some of the above assumptions are not satisfied.</p>
</section>
</section>
<section id="regression-fitting-ordinary-least-squares-ols" class="level1">
<h1>Regression fitting: ordinary least squares (OLS)</h1>
<p>By far the most common method for estimating linear regression coefficients is by minimizing the sum of the squares of the error terms (hence “least squares”).</p>
<p>The package we will use for linear regression fitting is called “<strong>statsmodels</strong>”. Install this package by typing the following in a terminal (or Anaconda Prompt):</p>
<p><strong>pip install statsmodels</strong></p>
<p>In fact, for the most part, we will only use the “api” subpackage of “statsmodels” as below. Here is the official documentation for the package if you want to learn more about it:</p>
<p>https://www.statsmodels.org/stable/index.html</p>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As mentioned above, we will estimate our regression coefficients using OLS (ordinary least squares). This can be done with the <code>OLS</code> function of <code>statsmodels</code>:</p>
<p>Syntax:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> statsmodels.regression.linear_model.OLS(endog, exog<span class="op">=</span><span class="va">None</span>, missing<span class="op">=</span><span class="st">'none'</span>, hasconst<span class="op">=</span><span class="va">None</span>, <span class="op">**</span>kwargs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>When we use this function, we can replace <code>statsmodels.regression.lineal_model</code> with <code>sm</code> (as imported above). The <code>endog</code> parameter is where we specify where the data for our dependent variable is, and the <code>exog</code> parameter is where we specify where our independent variables are. We usually set <code>missing=True</code> to tell Python that we want to get rid of all the rows in our regression data that have any missing values.</p>
<section id="example-1-estimating-a-stocks-alpha-and-beta-using-the-market-model" class="level2">
<h2 class="anchored" data-anchor-id="example-1-estimating-a-stocks-alpha-and-beta-using-the-market-model">Example 1: estimating a stock’s alpha and beta using the market model</h2>
<p>The market model (aka the “single-factor model” or the “single-index model”) is a linear regression model that relates the excess return on a stock to the excess returns on the market portfolio:</p>
<p><span class="math display">\[R_{i,t} - R_{f,t} = \alpha_i + \beta_i (R_{m,t} - R_{f,t}) + \epsilon_{i,t}\]</span></p>
<p>where: - <span class="math inline">\(R_{i,t}\)</span> is the return of firm <span class="math inline">\(i\)</span> at time <span class="math inline">\(t\)</span> - <span class="math inline">\(R_{m,t}\)</span> is the return of the market at time <span class="math inline">\(t\)</span> (we generally use the S&amp;P500 index as the market portfolio) - <span class="math inline">\(R_{f,t}\)</span> is the risk-free rate at time <span class="math inline">\(t\)</span> (most commonly the yield on the 1-month Tbill)</p>
<p>Below, we estimate this model for TSLA, using the data we gathered at the top of these lecture notes:</p>
<p>To “run” (i.e.&nbsp;“fit” or “estimate”) the regression, we use the <code>.fit()</code> function which can be applied after the <code>sm.OLS()</code> function. We store results in “res”:</p>
<div class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> sm.OLS(endog <span class="op">=</span> data[<span class="st">'TSLA'</span>]<span class="op">-</span>data[<span class="st">'RF'</span>], </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>             exog <span class="op">=</span> data[[<span class="st">'const'</span>,<span class="st">'Mkt-RF'</span>]], </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>             missing<span class="op">=</span><span class="st">'drop'</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>            ).fit()</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>res</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>&lt;statsmodels.regression.linear_model.RegressionResultsWrapper at 0x7fb7bb37f310&gt;</code></pre>
</div>
</div>
<p>The above shows that <code>res</code> is a “RegressionResultsWrapper”. We have not seen this kind of an object before. Check all the attributes of the results (<code>res</code>) object:</p>
<div class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">dir</span>(res))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['HC0_se', 'HC1_se', 'HC2_se', 'HC3_se', '_HCCM', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abat_diagonal', '_cache', '_data_attr', '_data_in_cache', '_get_robustcov_results', '_is_nested', '_use_t', '_wexog_singular_values', 'aic', 'bic', 'bse', 'centered_tss', 'compare_f_test', 'compare_lm_test', 'compare_lr_test', 'condition_number', 'conf_int', 'conf_int_el', 'cov_HC0', 'cov_HC1', 'cov_HC2', 'cov_HC3', 'cov_kwds', 'cov_params', 'cov_type', 'df_model', 'df_resid', 'eigenvals', 'el_test', 'ess', 'f_pvalue', 'f_test', 'fittedvalues', 'fvalue', 'get_influence', 'get_prediction', 'get_robustcov_results', 'info_criteria', 'initialize', 'k_constant', 'llf', 'load', 'model', 'mse_model', 'mse_resid', 'mse_total', 'nobs', 'normalized_cov_params', 'outlier_test', 'params', 'predict', 'pvalues', 'remove_data', 'resid', 'resid_pearson', 'rsquared', 'rsquared_adj', 'save', 'scale', 'ssr', 'summary', 'summary2', 't_test', 't_test_pairwise', 'tvalues', 'uncentered_tss', 'use_t', 'wald_test', 'wald_test_terms', 'wresid']</code></pre>
</div>
</div>
<p>Particularly important results are stored in <code>summary()</code>, <code>params</code>, <code>pvalues</code>, <code>tvalues</code>, <code>rsquared</code>. We’ll cover all of these below. As the name suggests, the <code>summary()</code> attribute contains a summary of the regression results:</p>
<div class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(res.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.155
Model:                            OLS   Adj. R-squared:                  0.146
Method:                 Least Squares   F-statistic:                     17.26
Date:                Wed, 22 Mar 2023   Prob (F-statistic):           7.18e-05
Time:                        07:32:31   Log-Likelihood:                 30.144
No. Observations:                  96   AIC:                            -56.29
Df Residuals:                      94   BIC:                            -51.16
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0416      0.019      2.186      0.031       0.004       0.079
Mkt-RF         1.8297      0.440      4.154      0.000       0.955       2.704
==============================================================================
Omnibus:                       29.750   Durbin-Watson:                   1.561
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               56.488
Skew:                           1.227   Prob(JB):                     5.42e-13
Kurtosis:                       5.846   Cond. No.                         24.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</section>
<section id="example-2-estimating-a-stocks-alpha-and-betas-using-the-fama-french-three-factor-model" class="level2">
<h2 class="anchored" data-anchor-id="example-2-estimating-a-stocks-alpha-and-betas-using-the-fama-french-three-factor-model">Example 2: estimating a stock’s alpha and beta(s) using the Fama-French three-factor model</h2>
<p>The Fama-French three factor model is a linear regression model that relates the excess return on a stock to the excess returns on the market portfolio and the returns on the SMB (small minus big) and HML (high minus low book-to-market) factors:</p>
<p><span class="math display">\[R_{i,t} - R_{f,t} = \alpha_i + \beta_{i,m} (R_{m,t} - R_{f,t}) + \beta_{i,smb}  R_{smb} + \beta_{i,hml} R_{hml} + \epsilon_{i,t}\]</span></p>
<p><strong>Challenge</strong>:</p>
<p>Estimate this regression for TSLA using the data we gathered at the top of these lecture notes.</p>
<div class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the regression and print the results</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>res3 <span class="op">=</span> sm.OLS(endog <span class="op">=</span> data[<span class="st">'TSLA'</span>]<span class="op">-</span>data[<span class="st">'RF'</span>], </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>             exog <span class="op">=</span> data[[<span class="st">'const'</span>,<span class="st">'Mkt-RF'</span>,<span class="st">'SMB'</span>,<span class="st">'HML'</span>]], </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>             missing<span class="op">=</span><span class="st">'drop'</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>            ).fit()</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>res3</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(res3.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.164
Model:                            OLS   Adj. R-squared:                  0.137
Method:                 Least Squares   F-statistic:                     6.036
Date:                Wed, 22 Mar 2023   Prob (F-statistic):           0.000847
Time:                        07:32:31   Log-Likelihood:                 30.677
No. Observations:                  96   AIC:                            -53.35
Df Residuals:                      92   BIC:                            -43.10
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0371      0.020      1.872      0.064      -0.002       0.076
Mkt-RF         1.8810      0.480      3.915      0.000       0.927       2.835
SMB            0.1931      0.794      0.243      0.808      -1.384       1.770
HML           -0.6717      0.667     -1.007      0.317      -1.997       0.653
==============================================================================
Omnibus:                       31.346   Durbin-Watson:                   1.587
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               62.467
Skew:                           1.268   Prob(JB):                     2.73e-14
Kurtosis:                       6.030   Cond. No.                         45.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</section>
</section>
<section id="interpreting-regression-results" class="level1">
<h1>Interpreting regression results</h1>
<section id="coefficients" class="level2">
<h2 class="anchored" data-anchor-id="coefficients">Coefficients</h2>
<p>The “const” row contains information about the firm’s <span class="math inline">\(\alpha\)</span> and the “Mkt-RF” row contains information about the firm’s <span class="math inline">\(\beta\)</span>. The <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> coefficient estimates themselves are in the “coef” column (<span class="math inline">\(\alpha = 0.0416\)</span>, and <span class="math inline">\(\beta = 1.83\)</span> in the single-factor model).</p>
<p>The “const” coefficient tells us what we should expect the return on TSLA to be on a day with no systematic shocks (i.e.&nbsp;a day with market return of 0).</p>
<p>The ‘Mkt-RF’ coefficient tells us how we should expect the return on TSLA to react to a given shock to the market portfolio (e.g.&nbsp;the 1.83 coefficient tells us that, on average, if the market goes up by 1%, TSLA goes up by 1.83%, and when the market goes down by 1%, TSLA goes down by 1.83%)</p>
<p>The results object (<code>res</code>) stores the regression coefficients in its <code>params</code> attribute:</p>
<div class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>res.params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<pre><code>const     0.041642
Mkt-RF    1.829738
dtype: float64</code></pre>
</div>
</div>
<p>Note that <code>res.params</code> is a Pandas Series, so we can access its individual elements using the index labels:</p>
<div class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Alpha = '</span>, res.params[<span class="st">'const'</span>])</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Market Beta = '</span>, res.params[<span class="st">'Mkt-RF'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Alpha =  0.041642456171143115
Market Beta =  1.8297380496913744</code></pre>
</div>
</div>
<p><strong>Challenge</strong>:</p>
<p>Print out (separately) the alpha and each of the betas from the three-factor model</p>
<div class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"three-factor alpha:"</span>, res3.params[<span class="st">'const'</span>])</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"three-factor market beta:"</span>, res3.params[<span class="st">'Mkt-RF'</span>])</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"SMB beta:"</span>, res3.params[<span class="st">'SMB'</span>])</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"HML beta:"</span>, res3.params[<span class="st">'HML'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>three-factor alpha: 0.037089953287553816
three-factor market beta: 1.881000087482544
SMB beta: 0.19308158602997738
HML beta: -0.6717493189696122</code></pre>
</div>
</div>
</section>
<section id="statistical-significance" class="level2">
<h2 class="anchored" data-anchor-id="statistical-significance">Statistical significance</h2>
<p><strong>The p-values</strong> are in the “P &gt; |t|” column. P-values lower than 0.05 allow us to conclude that the corresponding coefficient is statistically different from 0 at the 95% confidence level (i.e.&nbsp;reject the null hypothesis that the coefficient is 0). At the 99% confidence level, we would need the p-value to be smaller than 1% (1 minus the confidence level) to reject the null hypothesis that alpha = 0.</p>
<p><strong>The t-statistics</strong> for the two coefficients are in the “t” column. Loosely speaking a t-statistic that larger than 2 or smaller than -2 allows us to conclude that the corresponding coefficient is statistically different from 0 at the 95% confidence level (i.e.&nbsp;reject the null hypothesis that the coefficient is 0). In terms of statistical significance, the t-statistic does not provide any new information over the p-value.</p>
<p>The last two columns give us the 95% confidence interval for each coefficient.</p>
<p>For the market model, TSLA’s alpha has a p-value of 0.031 so we can conclude that it’s alpha is statistically significantly different from 0 at the 95% confidence level (but not at the 99% confidence level).</p>
<p>The fact that the alpha is positive and statistically different from 0 (at 95% level) means that, based on the single-factor model, TSLA seems to be <strong>undervalued</strong>. A negative alpha would mean the stock in <strong>overvalued</strong>.</p>
<p>If we can not reject the null hypothesis that alpha is 0, the conclusion is NOT that alpha = 0 and therefore the stock is correctly valued (since we can never “accept” a null hypothesis, we can only fail to reject). The conclusion is that we do not have enough evidence to claim that the stock is either undervalued or overvalued (which is not the same thing as saying that we have enough evidence to claim that the stock is correctly valued).</p>
<p>The results object (<code>res</code>) stores the regression p-values in its <code>pvalues</code> attribute:</p>
<div class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>res.pvalues</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<pre><code>const     0.031312
Mkt-RF    0.000072
dtype: float64</code></pre>
</div>
</div>
<p>The p-values can be accessed individually:</p>
<div class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Alpha p-value = "</span>, res.pvalues[<span class="st">'const'</span>])</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Beta p-value = "</span>, res.pvalues[<span class="st">'Mkt-RF'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Alpha p-value =  0.031311923663591416
Beta p-value =  7.182372372221883e-05</code></pre>
</div>
</div>
<p>T-statistics are stored in the <code>tvalues</code> attribute:</p>
<div class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>res.tvalues</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="46">
<pre><code>const     2.185832
Mkt-RF    4.154374
dtype: float64</code></pre>
</div>
</div>
<p>T-statistics of individual coefficients:</p>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Alpha t-stat = "</span>, res.tvalues[<span class="st">'const'</span>])</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Beta t-stat = "</span>, res.tvalues[<span class="st">'Mkt-RF'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Alpha t-stat =  2.1858319462947398
Beta t-stat =  4.154374466130978</code></pre>
</div>
</div>
<p><strong>Challenge</strong>:</p>
<p>Is TSLA mispriced (undervalued OR overvalued) at the 5% significance level with respect to the Fama-French 3-factor model?</p>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"TSLA mispriced? </span><span class="ch">\n</span><span class="st">"</span>, res3.pvalues[<span class="st">'const'</span>] <span class="op">&lt;</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>TSLA mispriced? 
 False</code></pre>
</div>
</div>
<p><strong>Challenge</strong>:</p>
<p>Does TSLA have a significant exposure (at 5% level) to either of the 3 factors in the Fama-French model?</p>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Significant market exposure?</span><span class="ch">\n</span><span class="st">'</span>, res3.pvalues[<span class="st">'Mkt-RF'</span>] <span class="op">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Significant exposure to SMB?</span><span class="ch">\n</span><span class="st">'</span>, res3.pvalues[<span class="st">'SMB'</span>] <span class="op">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Significant exposure to HML?</span><span class="ch">\n</span><span class="st">'</span>, res3.pvalues[<span class="st">'HML'</span>] <span class="op">&lt;</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Significant market exposure?
 True
Significant exposure to SMB?
 False
Significant exposure to HML?
 False</code></pre>
</div>
</div>
</section>
<section id="the-r-squared-coefficient" class="level2">
<h2 class="anchored" data-anchor-id="the-r-squared-coefficient">The R-squared coefficient</h2>
<p>The R-squared coefficient (top-right of the table, also referred to as the “coefficient of determination”) estimates the percentage of the total variance in the dependent variable (Y) that can be explained by the variance in the explanatory variable(s) (X).</p>
<p>In the context of our market-model example, the R-squared tells us the percentage of the firm’s total variance that is systematic in nature (i.e.&nbsp;non-diversifiable). The percentage of total variance that is idiosyncratic (diversifiable) equals 1 minus the R-squared.</p>
<p>The R-squared is stored in the <code>rsquared</code> attribute of the regression results object:</p>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>res.rsquared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="50">
<pre><code>0.1551232170825012</code></pre>
</div>
</div>
<p>Using the market model, our estimates of the percentage or total TSLA variance that is systematic vs idiosyncratic are:</p>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Percent of total variance that is systematic: "</span>, res.rsquared)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Percent of total variance that is idiosyncratic: "</span>, <span class="dv">1</span> <span class="op">-</span> res.rsquared)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Percent of total variance that is systematic:  0.1551232170825012
Percent of total variance that is idiosyncratic:  0.8448767829174988</code></pre>
</div>
</div>
<p><strong>Challenge</strong>:</p>
<p>What percentage of TSLA total variance can be diversified away under the Fama-French 3-factor model?</p>
<div class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Percent of total variance that is systematic: "</span>, res3.rsquared)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Percent of total variance that is idiosyncratic: "</span>, <span class="dv">1</span> <span class="op">-</span> res3.rsquared)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Percent of total variance that is systematic:  0.16445635788368973
Percent of total variance that is idiosyncratic:  0.8355436421163103</code></pre>
</div>
</div>
</section>
<section id="diagnostics-bottom-of-the-table" class="level2">
<h2 class="anchored" data-anchor-id="diagnostics-bottom-of-the-table">Diagnostics (bottom of the table):</h2>
<p>The regression table reports (at the bottom) a few statistics that help us understand if some of the assumption of the linear regression model are not satisfied.</p>
<ul>
<li><p>Durbin-Watson: tests for residual autocorrelation. Takes values in [0,4]. Below 2 means positive autocorr. Above 2 means negative aoutocorr. A value of 2 is perfect (means no autocorrelation).</p></li>
<li><p>Omnibus: tests normality of residuals. Prob(Omnibus) close to 0 means reject normality</p></li>
<li><p>JB: another normality test (null is skew=0, kurt=3). Prob(JB) close to 0 means rejection of normality</p></li>
<li><p>Cond. No: tests for multicollinearity. Over 100 is worrisome, but we still have to look at correlations between variables to determine if any of them need to be dropped.</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp("https:\/\/github\.com\/ionmihai\/ionmihai\.github\.io");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
</div> <!-- /content -->



</body></html>